name: Gatsby Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual run button
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Gatsby site
        run: npm run build

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Deploy only on push to main
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.test }}
          publish_dir: ./public
          force_orphan: true
